### ISSUE TITLE
Cool project - document background?

### ISSUE THREAD

**Issue by viblo** [poikilos/kivy-tkinter#1]
First I want to add that this is a cool and interesting looking project! 

I was looking at the README but couldnt understand the usage / why / background. Maybe you could add something why you wanted to created this and when it can be useful to the README (or other documentation)?

**Comment by Poikilos** [comment]
Sure, good idea. There were similar questions answered on:
- [the project announcement on Reddit](https://www.reddit.com/r/kivy/comments/kqh0gl/kivytkinter_a_wip_compatibility_layer_to_run_kivy/)
- [Kivy's Discord server](https://chat.kivy.org) under #your-projects: <https://discord.com/channels/423249981340778496/498526835337068581/795768163932569652>

I'll integrate some of those answers in the Readme, but if you look at the Reddit thread or scroll up to 1/4/2021 in the #my-projects channel on Kivy you'll see that conversation.

**Comment by viblo** [comment]
I actually came here from that reddit thread :)
But rereading, and especially checking what you wrote on discord gave a better background, thanks.

**Comment by Poikilos** [comment]
Considering the changes to readme.md, you can let me know if there is anything else that I explained better elsewhere, otherwise you can close if the readme is clear now.

**Comment by viblo** [comment]
👍
